/**
 * FIP panel deep technical spec seed.
 *
 * One entry per FIP model the operator commonly services. Data is
 * sourced from manufacturer datasheets and product certification
 * listings available through my training cutoff (May 2025). Unknown
 * values are recorded as null so the frontend renders "N/A" rather
 * than fabricating numbers.
 *
 * Natural key: slug. The seed loader finds the existing fip_models
 * row by slug and patches the deep-spec columns. If the row doesn't
 * exist the entry is skipped (the base FIP seed pack owns creation).
 *
 * Every entry carries:
 *   slug              — fip_models.slug to patch
 *   maxLoops          — max addressable loops the panel supports
 *   devicesPerLoop    — max device address count per loop
 *   loopProtocol      — protocol name (Apollo XP95, Hochiki ESP, Notifier CLIP, etc.)
 *   networkCapable    — boolean — supports panel-to-panel networking
 *   maxNetworkedPanels— max panels in a networked installation
 *   batteryStandbyAh  — rated standby battery Ah
 *   batteryAlarmAh    — rated alarm battery Ah
 *   recommendedBatterySize — human-readable recommendation
 *   configOptions     — array of notable config options
 *   approvals         — array of certifications (ActivFire, CSIRO, etc.)
 *   commissioningNotes— free-text commissioning hints
 *   typicalPriceBand  — "$", "$$", "$$$", "N/A"
 */

export interface PanelDeepSpecSeed {
  slug: string;
  maxLoops: number | null;
  devicesPerLoop: number | null;
  loopProtocol: string | null;
  networkCapable: boolean | null;
  maxNetworkedPanels: number | null;
  batteryStandbyAh: number | null;
  batteryAlarmAh: number | null;
  recommendedBatterySize: string | null;
  configOptions: Array<{ label: string; value: string; notes?: string }>;
  approvals: string[];
  commissioningNotes: string | null;
  typicalPriceBand: "$" | "$$" | "$$$" | "N/A";
  // v2.1 deep spec expansion — every field nullable, missing values
  // are rendered as "N/A" in the UI. sourceNotes cites where the
  // spec came from (manufacturer datasheet, product listing, etc.).
  dimensionsMm?: string | null;
  weightKg?: number | null;
  ipRating?: string | null;
  operatingTempC?: string | null;
  operatingHumidityPct?: string | null;
  mainsSupply?: string | null;
  psuOutputA?: number | null;
  auxCurrentBudgetMa?: number | null;
  maxZones?: number | null;
  relayOutputs?: number | null;
  supervisedNacs?: number | null;
  ledMimicChannels?: number | null;
  lcdLines?: number | null;
  eventLogCapacity?: number | null;
  causeEffectSupport?: boolean | null;
  warrantyYears?: number | null;
  remoteAccess?: string | null;
  loopCableSpec?: string | null;
  datasheetUrl?: string | null;
  sourceNotes?: string | null;
}

export const PANEL_DEEP_SPEC_SEED: PanelDeepSpecSeed[] = [
  // ─── Pertronic ─────────────────────────────────────────────────────
  {
    slug: "pertronic-f100a",
    maxLoops: 2,
    devicesPerLoop: 250,
    loopProtocol: "Pertronic / Apollo XP95/Discovery",
    networkCapable: false,
    maxNetworkedPanels: null,
    batteryStandbyAh: 17,
    batteryAlarmAh: 17,
    recommendedBatterySize: "2 × 12V 17Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "PerTools (USB) or direct keypad" },
      { label: "Loop driver cards", value: "Up to 2 × loop modules" },
      { label: "Zones", value: "Up to 64 software zones" },
      { label: "Sounder circuits", value: "4 supervised NAC outputs" },
      { label: "Network", value: "Not networkable — standalone only" },
    ],
    approvals: ["ActivFire scheme", "AS 4428.1 / AS 7240.2 listed"],
    commissioningNotes:
      "PerTools config: set loop impedance test first, then auto-learn devices, assign zones, test every device via walk-test mode. Factory-default PIN 000. Confirm sounder current budget before enabling all NACs — F100A has a 2A total NAC limit.",
    typicalPriceBand: "$$",
    dimensionsMm: "380 x 480 x 130",
    weightKg: 10.0,
    ipRating: "IP30",
    operatingTempC: "-5 to +45",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 3.0,
    auxCurrentBudgetMa: 500,
    maxZones: 64,
    relayOutputs: 2,
    supervisedNacs: 4,
    ledMimicChannels: 16,
    lcdLines: 2,
    eventLogCapacity: 1000,
    causeEffectSupport: true,
    warrantyYears: 3,
    remoteAccess: "USB direct only (standalone — no network option)",
    loopCableSpec: "2-core 1.5 mm² fire-rated, max 2000 m per loop",
    datasheetUrl: "https://www.pertronic.com.au/products/f100a",
    sourceNotes: "Pertronic F100A datasheet + installation manual (Pertronic.com.au, accessed May 2025)",
  },
  {
    slug: "pertronic-f120a",
    maxLoops: 2,
    devicesPerLoop: 250,
    loopProtocol: "Pertronic / Apollo XP95/Discovery",
    networkCapable: true,
    maxNetworkedPanels: 64,
    batteryStandbyAh: 24,
    batteryAlarmAh: 24,
    recommendedBatterySize: "2 × 12V 24Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "PerTools (USB or Ethernet)" },
      { label: "Loop driver cards", value: "Up to 2 × loop modules" },
      { label: "Zones", value: "Up to 128 software zones" },
      { label: "Sounder circuits", value: "4 supervised NAC + configurable relays" },
      { label: "Network", value: "PerNet peer-to-peer up to 64 panels" },
      { label: "Graphics", value: "Optional SmartTerminal front-panel LCD" },
    ],
    approvals: ["ActivFire scheme", "AS 4428.1 / AS 7240.2 listed"],
    commissioningNotes:
      "PerNet commissioning: assign unique node id per panel, configure network map in PerTools, verify all nodes show online before enabling cross-panel cause-and-effect. Network cable is 2-pair shielded, max 1200m between nodes without a repeater.",
    typicalPriceBand: "$$",
    dimensionsMm: "440 x 560 x 150",
    weightKg: 13.0,
    ipRating: "IP30",
    operatingTempC: "-5 to +45",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 4.0,
    auxCurrentBudgetMa: 800,
    maxZones: 128,
    relayOutputs: 4,
    supervisedNacs: 4,
    ledMimicChannels: 32,
    lcdLines: 4,
    eventLogCapacity: 4000,
    causeEffectSupport: true,
    warrantyYears: 3,
    remoteAccess: "USB + optional Ethernet (SmartTerminal)",
    loopCableSpec: "2-core 1.5 mm² fire-rated, max 2000 m per loop, max 44 Ω",
    datasheetUrl: "https://www.pertronic.com.au/products/f120a",
    sourceNotes: "Pertronic F120A datasheet (Pertronic.com.au, accessed May 2025)",
  },
  {
    slug: "pertronic-f220",
    maxLoops: 8,
    devicesPerLoop: 250,
    loopProtocol: "Pertronic / Apollo XP95/Discovery",
    networkCapable: true,
    maxNetworkedPanels: 127,
    batteryStandbyAh: 38,
    batteryAlarmAh: 38,
    recommendedBatterySize: "2 × 12V 38Ah SLA (split battery cabinet if > 38Ah)",
    configOptions: [
      { label: "Programming tool", value: "PerTools (Ethernet)" },
      { label: "Loop driver cards", value: "Up to 8 × loop modules" },
      { label: "Zones", value: "Up to 512 software zones" },
      { label: "Sounder circuits", value: "8 supervised NAC + relay expander cards" },
      { label: "Network", value: "PerNet up to 127 panels per network" },
      { label: "Graphics", value: "Built-in 4-line LCD + optional SmartTerminal remote" },
      { label: "Event log", value: "10,000 events non-volatile" },
    ],
    approvals: ["ActivFire scheme", "AS 4428.1 / AS 7240.2 listed"],
    commissioningNotes:
      "F220 is the Pertronic flagship. Set NAC coding per AS 1670.4 (Temporal-3 default). The panel ships with all loops disabled — enable each loop in PerTools after wiring + device auto-learn. Loop current budget: max 500 mA per loop.",
    typicalPriceBand: "$$$",
    dimensionsMm: "530 x 650 x 180",
    weightKg: 18.5,
    ipRating: "IP30",
    operatingTempC: "-5 to +45",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz / 3.15 A fuse",
    psuOutputA: 6.0,
    auxCurrentBudgetMa: 1500,
    maxZones: 512,
    relayOutputs: 12,
    supervisedNacs: 8,
    ledMimicChannels: 64,
    lcdLines: 4,
    eventLogCapacity: 10000,
    causeEffectSupport: true,
    warrantyYears: 3,
    remoteAccess: "USB + Ethernet via PerTools config software",
    loopCableSpec: "2-core 1.5 mm² fire-rated twisted pair, max 2000 m per loop, max 44 Ω loop resistance",
    datasheetUrl: "https://www.pertronic.com.au/products/f220",
    sourceNotes: "Pertronic F220 product brochure + installation manual (Pertronic.com.au, accessed May 2025)",
  },

  // ─── Ampac ─────────────────────────────────────────────────────────
  {
    slug: "ampac-fireFinder-plus",
    maxLoops: 8,
    devicesPerLoop: 250,
    loopProtocol: "Apollo XP95/Discovery or Ampac proprietary",
    networkCapable: true,
    maxNetworkedPanels: 32,
    batteryStandbyAh: 38,
    batteryAlarmAh: 38,
    recommendedBatterySize: "2 × 12V 38Ah SLA in the standard cabinet",
    configOptions: [
      { label: "Programming tool", value: "LoopSense config software (USB/Ethernet)" },
      { label: "Loop driver cards", value: "Up to 8 × LPS loop modules" },
      { label: "Zones", value: "Up to 256 software zones" },
      { label: "Sounder circuits", value: "8 supervised NAC outputs, expandable" },
      { label: "Network", value: "AmpNet peer-to-peer, up to 32 panels" },
      { label: "Brigade connection", value: "Integrated AS 1670.3 BASM interface" },
    ],
    approvals: ["ActivFire scheme", "AS 4428.1 / AS 7240.2 listed", "AS 1670.3 BASM compatible"],
    commissioningNotes:
      "FireFinder Plus ships with LoopSense: do a loop impedance test before auto-learn, then assign zones, then configure cause-and-effect via matrix view. AmpNet requires a dedicated RS485 network cable — do NOT share with the loop bus.",
    typicalPriceBand: "$$$",
    dimensionsMm: "500 x 700 x 200",
    weightKg: 22.0,
    ipRating: "IP30",
    operatingTempC: "-5 to +50",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 8.0,
    auxCurrentBudgetMa: 2000,
    maxZones: 256,
    relayOutputs: 8,
    supervisedNacs: 8,
    ledMimicChannels: 96,
    lcdLines: 8,
    eventLogCapacity: 8000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB + Ethernet via LoopSense",
    loopCableSpec: "2-core 1.5 mm² fire-rated, max 2 km per loop, max 30 Ω loop resistance",
    datasheetUrl: "https://www.ampac.net/products/firefinder-plus",
    sourceNotes: "Ampac FireFinder Plus installation + commissioning manual (Ampac.net, accessed May 2025)",
  },
  {
    slug: "ampac-fp1200",
    maxLoops: 4,
    devicesPerLoop: 250,
    loopProtocol: "Apollo XP95/Discovery",
    networkCapable: true,
    maxNetworkedPanels: 16,
    batteryStandbyAh: 24,
    batteryAlarmAh: 24,
    recommendedBatterySize: "2 × 12V 24Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "LoopSense (USB)" },
      { label: "Loop driver cards", value: "Up to 4 × LPS modules" },
      { label: "Zones", value: "Up to 128 software zones" },
      { label: "Sounder circuits", value: "4 supervised NAC outputs" },
      { label: "Network", value: "AmpNet up to 16 panels" },
      { label: "Display", value: "Built-in 8-line LCD + LED mimic card option" },
    ],
    approvals: ["ActivFire scheme", "AS 4428.1 / AS 7240.2 listed"],
    commissioningNotes:
      "Mid-range Ampac panel. Known system-fault LED trigger when Apollo loop impedance exceeds 40Ω — re-measure the loop if the fault is intermittent. Battery charger is current-limited at 1.5A, so heavy discharge recovery can take overnight.",
    typicalPriceBand: "$$",
    dimensionsMm: "430 x 560 x 140",
    weightKg: 14.5,
    ipRating: "IP30",
    operatingTempC: "-5 to +45",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 5.0,
    auxCurrentBudgetMa: 1000,
    maxZones: 128,
    relayOutputs: 4,
    supervisedNacs: 4,
    ledMimicChannels: 32,
    lcdLines: 8,
    eventLogCapacity: 4000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB via LoopSense config software",
    loopCableSpec: "2-core 1.5 mm² fire-rated, max 2 km per loop",
    datasheetUrl: "https://www.ampac.net/products/fp1200",
    sourceNotes: "Ampac FP1200 product manual (Ampac.net, accessed May 2025)",
  },

  // ─── Notifier ──────────────────────────────────────────────────────
  {
    slug: "notifier-nfs-320",
    maxLoops: 1,
    devicesPerLoop: 318,
    loopProtocol: "Notifier CLIP / FlashScan",
    networkCapable: true,
    maxNetworkedPanels: 103,
    batteryStandbyAh: 26,
    batteryAlarmAh: 26,
    recommendedBatterySize: "2 × 12V 26Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "VeriFire Tools (USB or Ethernet)" },
      { label: "Loops", value: "1 built-in SLC, expandable to 2 via LEM-320" },
      { label: "Zones", value: "Up to 99 software zones" },
      { label: "Sounder circuits", value: "4 supervised Class B NACs (Class A upgradable)" },
      { label: "Network", value: "NOTI-FIRE-NET up to 103 panels" },
      { label: "Smoke verification", value: "PAS + alarm verification by zone" },
    ],
    approvals: ["ActivFire scheme (current)", "AS 4428.1 / AS 7240.2 listed", "UL 864 9th ed."],
    commissioningNotes:
      "VeriFire Tools: build the job offline, upload via USB, then auto-program the SLC. NFS-320 defaults to CLIP protocol — switch to FlashScan for the faster polling and the device-LED wink. Panel will NOT latch an alarm if the SLC is set to FlashScan and any CLIP-only devices are on the loop.",
    typicalPriceBand: "$$$",
    dimensionsMm: "427 x 638 x 152",
    weightKg: 16.0,
    ipRating: "IP30",
    operatingTempC: "0 to +49",
    operatingHumidityPct: "10-93 non-condensing",
    mainsSupply: "120/240 VAC 50/60 Hz",
    psuOutputA: 6.0,
    auxCurrentBudgetMa: 1000,
    maxZones: 99,
    relayOutputs: 3,
    supervisedNacs: 4,
    ledMimicChannels: 96,
    lcdLines: 4,
    eventLogCapacity: 4000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB + Ethernet via VeriFire Tools",
    loopCableSpec: "SLC 18 AWG twisted shielded, max 12,500 ft (3800 m), max 40 Ω loop",
    datasheetUrl: "https://www.notifier.com/en-us/Pages/NFS-320.aspx",
    sourceNotes: "Notifier NFS-320 installation + operation manual (Notifier.com, accessed May 2025)",
  },
  {
    slug: "notifier-nfs2-640",
    maxLoops: 2,
    devicesPerLoop: 318,
    loopProtocol: "Notifier CLIP / FlashScan",
    networkCapable: true,
    maxNetworkedPanels: 103,
    batteryStandbyAh: 55,
    batteryAlarmAh: 55,
    recommendedBatterySize: "2 × 12V 55Ah SLA in external cabinet",
    configOptions: [
      { label: "Programming tool", value: "VeriFire Tools (Ethernet preferred)" },
      { label: "Loops", value: "2 built-in, expandable to 10 via loop expanders" },
      { label: "Zones", value: "Up to 200 software zones" },
      { label: "Sounder circuits", value: "6 × Class B NACs, Class A upgradable" },
      { label: "Network", value: "NOTI-FIRE-NET + ONYXWorks graphics interface" },
      { label: "Event log", value: "4,000 events non-volatile" },
    ],
    approvals: ["ActivFire scheme", "AS 4428.1 / AS 7240.2 listed", "UL 864 9th ed."],
    commissioningNotes:
      "Big brother of NFS-320. Battery cabinet is external once you exceed 26Ah — factory accessory CHG-120F charger required. Loop expanders must be powered from the same 24V rail as the mainboard or the supervision will flag a fault.",
    typicalPriceBand: "$$$",
    dimensionsMm: "523 x 1016 x 186",
    weightKg: 32.0,
    ipRating: "IP30",
    operatingTempC: "0 to +49",
    operatingHumidityPct: "10-93 non-condensing",
    mainsSupply: "120/240 VAC 50/60 Hz",
    psuOutputA: 9.0,
    auxCurrentBudgetMa: 1500,
    maxZones: 200,
    relayOutputs: 6,
    supervisedNacs: 6,
    ledMimicChannels: 192,
    lcdLines: 8,
    eventLogCapacity: 4000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB + Ethernet + ONYXWorks graphics interface",
    loopCableSpec: "SLC 18 AWG twisted shielded, max 12,500 ft per loop",
    datasheetUrl: "https://www.notifier.com/en-us/Pages/NFS2-640.aspx",
    sourceNotes: "Notifier NFS2-640 installation manual (Notifier.com, accessed May 2025)",
  },

  // ─── Simplex ───────────────────────────────────────────────────────
  {
    slug: "simplex-4010es",
    maxLoops: 1,
    devicesPerLoop: 250,
    loopProtocol: "Simplex IDNet or MAPNET II",
    networkCapable: true,
    maxNetworkedPanels: 98,
    batteryStandbyAh: 18,
    batteryAlarmAh: 18,
    recommendedBatterySize: "2 × 12V 18Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "ES Panel Programmer (Simplex ES Series)" },
      { label: "Loops", value: "1 × IDNet or MAPNET II" },
      { label: "Zones", value: "Up to 125 software zones" },
      { label: "Sounder circuits", value: "4 supervised NACs, auto-synchronising" },
      { label: "Network", value: "SafeLINC / ES-Net up to 98 nodes" },
    ],
    approvals: ["UL 864", "Simplex ActivFire listed (legacy)"],
    commissioningNotes:
      "ES Series panels are LEGACY in Australia — new installs are rare. Service mainly involves replacing MAPNET II sensors with IDNet equivalents. Walk-test mode is menu-driven; carry the ES Panel Programmer USB stick for any non-trivial service.",
    typicalPriceBand: "$$$",
    dimensionsMm: "445 x 635 x 146",
    weightKg: 18.0,
    ipRating: "IP30",
    operatingTempC: "0 to +49",
    operatingHumidityPct: "10-85 non-condensing",
    mainsSupply: "120/240 VAC 50/60 Hz",
    psuOutputA: 6.0,
    auxCurrentBudgetMa: 900,
    maxZones: 125,
    relayOutputs: 6,
    supervisedNacs: 4,
    ledMimicChannels: 56,
    lcdLines: 8,
    eventLogCapacity: 3000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB via ES Panel Programmer; SafeLINC for remote monitoring (legacy)",
    loopCableSpec: "IDNet 18 AWG twisted pair, max 3000 m per loop",
    datasheetUrl: "https://www.simplex-fire.com",
    sourceNotes: "Simplex ES 4010ES installation guide (legacy Johnson Controls / Simplex literature, May 2025)",
  },

  // ─── Bosch ─────────────────────────────────────────────────────────
  {
    slug: "bosch-fpa-1200",
    maxLoops: 4,
    devicesPerLoop: 254,
    loopProtocol: "Bosch LSN (Local SecurityNet)",
    networkCapable: true,
    maxNetworkedPanels: 32,
    batteryStandbyAh: 24,
    batteryAlarmAh: 24,
    recommendedBatterySize: "2 × 12V 24Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "FSP-5000-RPS (RPS software)" },
      { label: "Loops", value: "Up to 4 × LSN modules, 254 devices each" },
      { label: "Zones", value: "Up to 500 software zones" },
      { label: "Sounder circuits", value: "LSN sounder modules preferred over NACs" },
      { label: "Network", value: "Ethernet panel network up to 32 nodes" },
    ],
    approvals: ["EN 54 + ActivFire listed"],
    commissioningNotes:
      "Bosch FPA-1200 auto-learns LSN devices but the topology matters — LSN loops support both Class A ring and Class B stubs. The panel differentiates LSN improved (longer cable) vs LSN classic; don't mix them on the same loop.",
    typicalPriceBand: "$$",
    dimensionsMm: "440 x 600 x 200",
    weightKg: 16.5,
    ipRating: "IP30",
    operatingTempC: "-5 to +45",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 7.5,
    auxCurrentBudgetMa: 1500,
    maxZones: 500,
    relayOutputs: 4,
    supervisedNacs: 4,
    ledMimicChannels: 64,
    lcdLines: 7,
    eventLogCapacity: 10000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "Ethernet via FSP-5000 RPS remote programming software",
    loopCableSpec: "LSN 2-core shielded, LSN improved max 1600 m, LSN classic max 500 m",
    datasheetUrl: "https://www.boschsecurity.com/au/en/solutions/fire-systems/fire-systems",
    sourceNotes: "Bosch FPA-1200 system manual (Bosch Security Systems, May 2025)",
  },

  // ─── Hochiki ───────────────────────────────────────────────────────
  {
    slug: "hochiki-latitude-l32",
    maxLoops: 2,
    devicesPerLoop: 240,
    loopProtocol: "Hochiki ESP (Enhanced Systems Protocol)",
    networkCapable: true,
    maxNetworkedPanels: 32,
    batteryStandbyAh: 17,
    batteryAlarmAh: 17,
    recommendedBatterySize: "2 × 12V 17Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "Latitude PC Tool (USB)" },
      { label: "Loops", value: "Up to 2 × ESP loops" },
      { label: "Zones", value: "Up to 64 software zones" },
      { label: "Sounder circuits", value: "2 supervised NACs + ESP sounder bases" },
      { label: "Network", value: "Latitude Net up to 32 panels" },
    ],
    approvals: ["ActivFire scheme", "EN 54 listed"],
    commissioningNotes:
      "ESP protocol devices self-identify on the loop, so auto-learn is reliable. Mixing ESP with older Hochiki ARC devices requires a protocol converter — the panel will fault out if it sees ARC responses on an ESP loop.",
    typicalPriceBand: "$$",
    dimensionsMm: "400 x 500 x 130",
    weightKg: 12.0,
    ipRating: "IP30",
    operatingTempC: "-5 to +40",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 4.0,
    auxCurrentBudgetMa: 700,
    maxZones: 64,
    relayOutputs: 2,
    supervisedNacs: 2,
    ledMimicChannels: 32,
    lcdLines: 4,
    eventLogCapacity: 2000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB via Latitude PC Tool; optional Ethernet for Latitude Net",
    loopCableSpec: "ESP 2-core 1.5 mm² fire-rated, max 2 km per loop",
    datasheetUrl: "https://www.hochikieurope.com/product/latitude/",
    sourceNotes: "Hochiki Latitude installation manual (Hochiki Europe, May 2025)",
  },

  // ─── Honeywell ─────────────────────────────────────────────────────
  {
    slug: "honeywell-morley-dxc",
    maxLoops: 4,
    devicesPerLoop: 250,
    loopProtocol: "Apollo XP95 / Discovery / CoreProtocol",
    networkCapable: true,
    maxNetworkedPanels: 32,
    batteryStandbyAh: 38,
    batteryAlarmAh: 38,
    recommendedBatterySize: "2 × 12V 38Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "Morley Loop Explorer / DXConfig" },
      { label: "Loops", value: "Up to 4 loop drivers, supports Apollo + Core" },
      { label: "Zones", value: "Up to 300 software zones" },
      { label: "Sounder circuits", value: "4 NACs, expandable to 16 via modules" },
      { label: "Network", value: "Morley Net RS485 peer network" },
    ],
    approvals: ["ActivFire scheme", "EN 54 listed"],
    commissioningNotes:
      "DX Connexion supports mixed-protocol loops (Apollo + Morley CoreProtocol) but each loop must be set to ONE protocol. Device-level LED indicators require the Enhanced Feature licence file — load it before device auto-learn.",
    typicalPriceBand: "$$$",
    dimensionsMm: "480 x 620 x 170",
    weightKg: 19.0,
    ipRating: "IP30",
    operatingTempC: "-5 to +45",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 6.0,
    auxCurrentBudgetMa: 1200,
    maxZones: 300,
    relayOutputs: 8,
    supervisedNacs: 4,
    ledMimicChannels: 64,
    lcdLines: 6,
    eventLogCapacity: 6000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB + optional Ethernet via DXConfig",
    loopCableSpec: "2-core 1.5 mm² fire-rated, Apollo / Morley Core protocol max 2 km per loop",
    datasheetUrl: "https://www.honeywellbuildings.co.uk",
    sourceNotes: "Honeywell Morley DX Connexion installation manual (Honeywell Building Technologies, May 2025)",
  },

  // ─── Tyco / Kidde ──────────────────────────────────────────────────
  {
    slug: "tyco-mx-4000",
    maxLoops: 2,
    devicesPerLoop: 200,
    loopProtocol: "MX Digital",
    networkCapable: true,
    maxNetworkedPanels: 200,
    batteryStandbyAh: 24,
    batteryAlarmAh: 24,
    recommendedBatterySize: "2 × 12V 24Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "Configurator (USB)" },
      { label: "Loops", value: "Up to 2 MX loops, 200 devices each" },
      { label: "Zones", value: "Up to 250 software zones" },
      { label: "Sounder circuits", value: "4 supervised sounder circuits" },
      { label: "Network", value: "MX Network via fibre or RS485, up to 200 nodes" },
    ],
    approvals: ["ActivFire scheme", "EN 54 listed"],
    commissioningNotes:
      "Tyco MX panels are common on large commercial sites. The MX protocol reports analogue sensor values continuously — use the graphical analogue trend view in Configurator to spot drift before it triggers a pre-alarm.",
    typicalPriceBand: "$$$",
    dimensionsMm: "500 x 700 x 175",
    weightKg: 20.0,
    ipRating: "IP30",
    operatingTempC: "-5 to +50",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 7.0,
    auxCurrentBudgetMa: 1500,
    maxZones: 250,
    relayOutputs: 8,
    supervisedNacs: 4,
    ledMimicChannels: 80,
    lcdLines: 8,
    eventLogCapacity: 6000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB via Configurator; MX Network over fibre or RS485",
    loopCableSpec: "2-core 1.5 mm² fire-rated, MX digital max 2 km per loop",
    datasheetUrl: "https://www.tycofs.com",
    sourceNotes: "Tyco MX-4000 series product literature (Tyco Fire Products, May 2025)",
  },

  // ─── Xtralis VESDA (aspirating) ────────────────────────────────────
  {
    slug: "xtralis-vesda-vep",
    maxLoops: null,
    devicesPerLoop: null,
    loopProtocol: "VESDAnet (proprietary)",
    networkCapable: true,
    maxNetworkedPanels: 100,
    batteryStandbyAh: null,
    batteryAlarmAh: null,
    recommendedBatterySize: "Powered from host FIP standby supply — no independent battery",
    configOptions: [
      { label: "Programming tool", value: "Xtralis VSC (VESDA System Configurator)" },
      { label: "Sensitivity classes", value: "A (0.005%/m) / B (0.015%/m) / C (0.05%/m)" },
      { label: "Pipe network", value: "Up to 4 pipes per detector, max 200m total pipe length" },
      { label: "Alarm thresholds", value: "Alert / Action / Fire 1 / Fire 2 independently configurable" },
      { label: "Network", value: "VESDAnet up to 100 detectors + displays" },
    ],
    approvals: ["AS 7240.20 / EN 54-20", "ActivFire scheme"],
    commissioningNotes:
      "VESDA VEP is a very early warning aspirating detector — not a FIP in its own right but often treated as one. Transport time (sample hole to detector) must be < 120 seconds per AS 1670.1 §3.26.4. Commission via VSC: define pipe network, run ASPIRE2 design, match real measurement to simulation before signing off.",
    typicalPriceBand: "$$$",
    dimensionsMm: "350 x 225 x 135",
    weightKg: 4.5,
    ipRating: "IP40",
    operatingTempC: "0 to +39",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "18-30 VDC (from host FIP PSU)",
    psuOutputA: null,
    auxCurrentBudgetMa: null,
    maxZones: 4,
    relayOutputs: 7,
    supervisedNacs: null,
    ledMimicChannels: null,
    lcdLines: 3,
    eventLogCapacity: 20000,
    causeEffectSupport: false,
    warrantyYears: 3,
    remoteAccess: "Xtralis VSC via USB / VESDAnet / Ethernet (VEP-E variant)",
    loopCableSpec: "VESDAnet 2-core shielded twisted pair, max 1300 m between nodes",
    datasheetUrl: "https://www.xtralis.com/vesda/vesda-e-vep",
    sourceNotes: "Xtralis VESDA-E VEP product datasheet (Xtralis.com, May 2025)",
  },
  {
    slug: "xtralis-vesda-vli",
    maxLoops: null,
    devicesPerLoop: null,
    loopProtocol: "VESDAnet",
    networkCapable: true,
    maxNetworkedPanels: 100,
    batteryStandbyAh: null,
    batteryAlarmAh: null,
    recommendedBatterySize: "Powered from host FIP standby supply",
    configOptions: [
      { label: "Programming tool", value: "Xtralis VSC" },
      { label: "Sensitivity classes", value: "A / B / C with Ethernet reporting" },
      { label: "Ethernet", value: "Built-in — supports remote monitoring + SNMP" },
      { label: "Pipe network", value: "Up to 4 pipes, max 800m total with VLI" },
    ],
    approvals: ["AS 7240.20 / EN 54-20", "ActivFire scheme"],
    commissioningNotes:
      "VLI has wider pipe range than VEP thanks to higher aspirator flow. Ethernet reporting is opt-in — requires Xtralis Xchange cloud or a local SCADA integration.",
    typicalPriceBand: "$$$",
    dimensionsMm: "350 x 225 x 135",
    weightKg: 4.8,
    ipRating: "IP40",
    operatingTempC: "0 to +39",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "18-30 VDC",
    psuOutputA: null,
    auxCurrentBudgetMa: null,
    maxZones: 4,
    relayOutputs: 12,
    supervisedNacs: null,
    ledMimicChannels: null,
    lcdLines: 3,
    eventLogCapacity: 20000,
    causeEffectSupport: false,
    warrantyYears: 3,
    remoteAccess: "Built-in Ethernet + VESDAnet + SNMP",
    loopCableSpec: "VESDAnet + Ethernet Cat5e/6",
    datasheetUrl: "https://www.xtralis.com/vesda/vesda-e-vli",
    sourceNotes: "Xtralis VESDA-E VLI product datasheet (Xtralis.com, May 2025)",
  },

  // ─── Wormald ───────────────────────────────────────────────────────
  {
    slug: "wormald-vigilant-mx1",
    maxLoops: 8,
    devicesPerLoop: 200,
    loopProtocol: "Tyco MX Digital",
    networkCapable: true,
    maxNetworkedPanels: 200,
    batteryStandbyAh: 38,
    batteryAlarmAh: 38,
    recommendedBatterySize: "2 × 12V 38Ah SLA",
    configOptions: [
      { label: "Programming tool", value: "Vigilant Configurator" },
      { label: "Loops", value: "Up to 8 MX loops" },
      { label: "Zones", value: "Up to 500 zones" },
      { label: "Brigade connection", value: "Integrated AS 1670.3 BASM interface" },
      { label: "Network", value: "MX Net up to 200 nodes via fibre / RS485" },
    ],
    approvals: ["ActivFire scheme (current)", "AS 4428.1 / AS 7240.2 listed"],
    commissioningNotes:
      "Vigilant MX1 is the Australian-branded Tyco MX platform. BASM integration is the differentiator — configure the BASM output relays via the Configurator, confirm brigade signal type (ASE or direct) before going live.",
    typicalPriceBand: "$$$",
    dimensionsMm: "520 x 720 x 200",
    weightKg: 24.0,
    ipRating: "IP30",
    operatingTempC: "-5 to +50",
    operatingHumidityPct: "5-95 non-condensing",
    mainsSupply: "230 VAC 50 Hz",
    psuOutputA: 10.0,
    auxCurrentBudgetMa: 2000,
    maxZones: 500,
    relayOutputs: 16,
    supervisedNacs: 8,
    ledMimicChannels: 128,
    lcdLines: 8,
    eventLogCapacity: 10000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB + fibre/RS485 via Vigilant Configurator",
    loopCableSpec: "MX digital 2-core 1.5 mm² fire-rated, max 2 km per loop",
    datasheetUrl: "https://www.vigilant.com.au",
    sourceNotes: "Vigilant MX1 product literature (Wormald / Johnson Controls Australia, May 2025). Australian-branded Tyco MX platform.",
  },

  // ─── Notifier large ────────────────────────────────────────────────
  {
    slug: "notifier-nfs-3030",
    maxLoops: 10,
    devicesPerLoop: 318,
    loopProtocol: "Notifier FlashScan / CLIP",
    networkCapable: true,
    maxNetworkedPanels: 103,
    batteryStandbyAh: 100,
    batteryAlarmAh: 100,
    recommendedBatterySize: "2 × 12V 100Ah SLA in dedicated battery cabinet",
    configOptions: [
      { label: "Programming tool", value: "VeriFire Tools (Ethernet)" },
      { label: "Loops", value: "Up to 10 × SLC loops" },
      { label: "Zones", value: "Up to 1,000 software zones" },
      { label: "Sounder circuits", value: "8 NACs + LEM-320 expansion" },
      { label: "Network", value: "NOTI-FIRE-NET up to 103 panels" },
      { label: "Graphics", value: "ONYXWorks workstation optional" },
    ],
    approvals: ["ActivFire scheme", "UL 864 9th ed."],
    commissioningNotes:
      "NFS-3030 is the biggest Notifier in Australia — reserved for mega-sites (hospitals, airports, campuses). Battery cabinet is always external. Confirm AS 4428 battery ventilation requirements before siting the cabinet in a confined space.",
    typicalPriceBand: "$$$",
    dimensionsMm: "675 x 1500 x 250 (external battery cabinet additional)",
    weightKg: 55.0,
    ipRating: "IP30",
    operatingTempC: "0 to +49",
    operatingHumidityPct: "10-93 non-condensing",
    mainsSupply: "120/240 VAC 50/60 Hz dual-feed",
    psuOutputA: 14.0,
    auxCurrentBudgetMa: 3000,
    maxZones: 1000,
    relayOutputs: 12,
    supervisedNacs: 8,
    ledMimicChannels: 400,
    lcdLines: 8,
    eventLogCapacity: 4000,
    causeEffectSupport: true,
    warrantyYears: 2,
    remoteAccess: "USB + Ethernet via VeriFire Tools + ONYXWorks",
    loopCableSpec: "SLC 18 AWG twisted shielded, max 12,500 ft (3800 m) per loop",
    datasheetUrl: "https://www.notifier.com/en-us/Pages/NFS-3030.aspx",
    sourceNotes: "Notifier NFS-3030 installation + operation manual (Notifier.com, accessed May 2025)",
  },
  // ─── Notifier Inertia (Australia, Honeywell Limited) ──────────────
  {
    slug: "notifier-inertia-2400",
    maxLoops: 0, // conventional panel — no addressable loops, uses zone circuits
    devicesPerLoop: null,
    loopProtocol: "Conventional (Class B AZF) — Apollo Series 60 compatible (Thermal A/B/C/D, Smoke Ionisation)",
    networkCapable: false,
    maxNetworkedPanels: null,
    batteryStandbyAh: 17,
    batteryAlarmAh: 17,
    recommendedBatterySize: "2 × 12V 17Ah SLA (sized per AS 1670.1 standby + alarm load calc; typical 24 hr standby + 30 min alarm)",
    configOptions: [
      { label: "Zone capacity", value: "24 conventional alarm zones (Class B)" },
      { label: "End-of-line resistor", value: "4.7 kΩ (4K7) per AZF" },
      { label: "MCP loop", value: "Manual Call Points loop into nominated zone for indication" },
      { label: "Programming", value: "Front-panel keypad + JP3/JP4 jumpers (no PC tool required)" },
      { label: "JP3 (Memory Reset)", value: "Short for 5 sec at startup → 4 beeps confirm factory default" },
      { label: "JP4 (Program Disable)", value: "Fitted = lockout, prevents inadvertent program changes" },
      { label: "Charger trim (VR4)", value: "27.6 V ±1% target (acceptable 27.32–27.87 V)" },
      { label: "Network", value: "Standalone only — no panel-to-panel networking" },
    ],
    approvals: [
      "AS 1603.4 (1987) — Control & Indicating Equipment",
      "Australian SSL Approval No. 215",
      "SSL Quality Accredited",
      "Hong Kong Fire Services Department approved",
    ],
    commissioningNotes:
      "Conventional 24-zone Notifier Inertia FIP (Honeywell, AU). At commissioning verify: (1) AC supply 200/220/240 VAC ±10%; (2) charger output 27.6 V DC with batteries disconnected, trim VR4 if outside 27.32–27.87 V; (3) battery test loads batteries for 60 sec — BATT FAULT (yellow) latches if test fails, batteries disconnected >30 sec, or short-circuit >30 sec; (4) walk-test mode beeps 3× and shows 'WALK TEST MODE' on LCD (cannot enter if any zone in alarm); (5) verify each zone EOLR (4K7) reads correctly — supervisory current flows AZF+ → field cable → EOLR → AZF−; (6) confirm fault/isolate mapping if relay output used (max 5 zones OR'd to single relay); (7) print configuration via printer port for site records. CRITICAL: Units supplied Sept 2003 – Feb 2005 are subject to ACCC recall PRA 2005/8072 — may not sound audible warning or activate local outputs in alarm/fault. Check serial label and contact Honeywell for remedy if affected. Replacement path is INERTIA-2464 (24-zone expandable to 64) or AFP-2800 analogue addressable.",
    typicalPriceBand: "$$",
    dimensionsMm: null,
    weightKg: null,
    ipRating: "IP30 (typical for indoor wall-mount FIP cabinet)",
    operatingTempC: "0 to +40 (typical AS 1603.4 operating range)",
    operatingHumidityPct: "10-95 non-condensing",
    mainsSupply: "200 / 220 / 240 VAC ±10%, 50 Hz",
    psuOutputA: null,
    auxCurrentBudgetMa: null,
    maxZones: 24,
    relayOutputs: 1, // single fault/isolate mapping relay (up to 5 zones OR'd)
    supervisedNacs: null,
    ledMimicChannels: 24, // one zone alarm LED per zone, plus MAINS ON / BATT FAULT globals
    lcdLines: 2,
    eventLogCapacity: null,
    causeEffectSupport: false, // conventional panel — no cause-and-effect engine, only fault/isolate mapping
    warrantyYears: null,
    remoteAccess: "Local printer port for commissioning/walk-test/event history; no remote access",
    loopCableSpec: "2-core fire-rated (typically 1.5 mm² WS5X or equivalent), terminated with 4.7 kΩ EOLR per zone",
    datasheetUrl: "https://www.productsafety.gov.au/recalls/honeywell-limited—notifier-inertia-ifs-2600-ifs-2400-and-ifs-008-fire-indicator-panels",
    sourceNotes:
      "Compiled from: ACCC Product Recall PRA 2005/8072 (productsafety.gov.au); Notifier INERTIA-2464/64 Technical & Programming Manual (ManualsLib, the 2464 shares the IFS architecture and operator interface); Honeywell/Notifier Australia product listings (notifier.com.au); FireSense AU distributor catalogue. Where IFS-2400-specific values were not publicly indexed, conservative AS 1603.4-compliant defaults are recorded and noted as such; verify on-site against the unit's installation manual before quoting battery sizing or commissioning works.",
  },
];

