import { Router, type IRouter } from "express";
import healthRouter from "./health";
import anthropicRouter from "./anthropic";
import jobsRouter from "./jobs";
import notesRouter from "./notes";
import toolboxRouter from "./toolbox";
import dashboardRouter from "./dashboard";
import todosRouter from "./todos";
import projectsRouter from "./projects";
import wipRouter from "./wip";
import quotesRouter from "./quotes-route";
import defectsRouter from "./defects-route";
import invoicesRouter from "./invoices-route";
import suppliersRouter from "./suppliers-route";
import kpiRouter from "./kpi";
import contextualChatRouter from "./contextual-chat";
import analyticsRouter from "./analytics";
import scheduleEventsRouter from "./schedule-events";
import pmRouter from "./pm";
import onCallRouter from "./on-call";
import clientsRouter from "./clients";
import chatHistoryRouter from "./chat-history";
import authRouter from "./auth";
import uptickRouter from "./uptick";
import fipRouter from "./fip";
import fipAssistantRouter from "./fip-assistant";
import chatAgentRouter from "./chat-agent";
import estimatesRouter from "./estimates";
import metricsRouter from "./metrics";
import remindersRouter from "./reminders";
import diagRouter from "./diag";

const router: IRouter = Router();

router.use(healthRouter);
router.use(anthropicRouter);
router.use(jobsRouter);
router.use(notesRouter);
router.use(toolboxRouter);
router.use(dashboardRouter);
router.use(todosRouter);
router.use(projectsRouter);
router.use(wipRouter);
router.use(quotesRouter);
router.use(defectsRouter);
router.use(invoicesRouter);
router.use(suppliersRouter);
router.use(kpiRouter);
router.use(contextualChatRouter);
router.use(analyticsRouter);
router.use(scheduleEventsRouter);
router.use(pmRouter);
router.use(onCallRouter);
router.use(clientsRouter);
router.use(chatHistoryRouter);
router.use(authRouter);
router.use(uptickRouter);
router.use(fipRouter);
router.use(fipAssistantRouter);
router.use(chatAgentRouter);
router.use(estimatesRouter);
router.use(metricsRouter);
router.use(remindersRouter);
router.use(diagRouter);

export default router;
